describe("Sign Up", () => {
  it("signup correctly", () => {
    cy.visit("/")
    cy.contains("Signup").click()
    cy.url().should("include", "/signup")
    cy.get("input[name=email]")
      .type("azizforwork@gmail.com")
      .should("have.value", "azizforwork@gmail.com")
    cy.get("input[name=name]")
      .type("Mohammad Aziz")
      .should("have.value", "Mohammad Aziz")
    cy.get("input[name=username]")
      .type("aziz")
      .should("have.value", "aziz")
    cy.get("input[name=password]")
      .type("mypass")
      .should("have.value", "mypass")
    cy.get("input[type=submit]").click()
    cy.url().should("include", "/")
  })
})
