describe("Login", () => {
  it("signup correctly", () => {
    cy.visit(`http://localhost:3000`)
    cy.contains("Signup").click()
    cy.url().should("include", "/signup")
    cy.get("#email")
      .type("azizforwork@gmail.com")
      .should("have.value", "azizforwork@gmail.com")
    cy.get("#name")
      .type("Mohammad Aziz")
      .should("have.value", "Mohammad Aziz")
    cy.get("#username")
      .type("aziz")
      .should("have.value", "aziz")
    cy.get("#password")
      .type("mypass")
      .should("have.value", "mypass")
    cy.get("#signup").click()
    cy.url().should("include", "/")
  })
})
